apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: application
  namespace: default
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: myresolver
  routes:
    # sitemaps
    - match: Host(`application.pocketcoach.fit`)
      kind: Rule
      services:
        - name: application-helper 
          port: 80

