apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: application
  namespace: default
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: myresolver
  routes:
    - match: Host(`application.pocketcoach.fit`) && PathPrefix(`/.well-known`)
      kind: Rule
      services:
        - name: application-helper 
          port: 80
    - match: Host(`application.pocketcoach.fit`)
      kind: Rule
      middlewares:
        - name: add-prefix-for-blog 
      services:
        - name: website 
          port: 80

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: add-prefix-for-blog
spec:
  addPrefix:
    prefix: /descarga-de-la-app-pocket-coach

