apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: test
  namespace: argocd
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: myresolver
  routes:
    - kind: Rule
      match: Host(`cd.pocketcoach.nvim.live`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`cd.pocketcoach.nvim.live`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c

---

kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: argocd
  name: dummy
  labels:
    app: dummy

spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - name: dummy
          image: traefik/whoami
          ports:
            - name: web
              containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: dummy
  namespace: argocd
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 80
  selector:
    app: dummy

