apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: funnel-frontend
  namespace: default
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: myresolver
  # -------------------------------------------------------------
  #                         ROUTES
  # -------------------------------------------------------------
  routes:
    # funnel-frontend
    # ----------------------------------------------------------- 
    - match: Host(`pocketcoach.fit`) && PathPrefix(`/promo`)
      kind: Rule
      services:
        - name: funnel-frontend
          port: 80
    # ----------------------------------------------------------- 
    - match: Host(`pocketcoach.promo`)
      kind: Rule
      middlewares:
        - name: add-prefix-promo
      services:
        - name: funnel-frontend
          port: 80
    # ----------------------------------------------------------- 
    - match: Host(`pocketcoach.promo`) && PathPrefix(`/promo`)
      kind: Rule
      services:
        - name: funnel-frontend
          port: 80
    # ----------------------------------------------------------- 
    # - match: Host(`cdf.promo`) && PathPrefix(`/promo`)
    #   kind: Rule
    #   # middlewares:
    #   #   - name: strip-prefix-funnel-frontend
    #   services:
    #     - name: funnel-frontend
    #       port: 80
