apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-index
spec:
  selector:
    matchLabels:
      app: food-index
  replicas: 1
  template:
    metadata:
      labels:
        app: food-index # has to match .spec.selector.matchLabels
    spec:
      imagePullSecrets:
        - name: registry-key-secret
      containers:
        - name: food-index
          image: ghcr.io/pocketcoachfit/food-index:v1.0.1
          ports:
            - name: main
              containerPort: 3000
          volumeMounts:
            - name: local-envfile
              mountPath: /app/.env.local
      volumes:
        - name: local-envfile
          hostPath:
            path: /secrets/food-index/.env.local
            type: File

---
apiVersion: v1
kind: Service
metadata:
  name: food-index
spec:
  selector:
    app: food-index
  ports:
    - protocol: TCP
      port: 80
      targetPort: main

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: food-index
  namespace: default
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: myresolver
  routes:
    - match: Host(`pocketcoach.fit`) && PathPrefix(`/db`)
      kind: Rule
      middlewares:
        - name: strip-food-index
      services:
        - name: food-index
          port: 80

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-food-index
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /db
