apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-backend
  template:
    metadata:
      labels:
        app: food-backend
    spec:
      imagePullSecrets:
        - name: registry-key-secret
      containers:
        - name: hello
          image: ghcr.io/pocketcoachfit/food-backend:v1.0.1
          ports:
            - name: main
              containerPort: 3000
          env:
            - name: PRODUCT_PICTURES_BASE_URL
              value: https://pocketcoach.club/images/uploads/alimentos
            - name: RECIPE_PICTURES_BASE_URL
              value: https://pocketcoach.club/images/uploads/comidas
          volumeMounts:
            - name: envfile
              mountPath: /app/.env
      volumes:
        - name: envfile
          hostPath:
            path: /secrets/food-backend/.env
            type: File

---
kind: Service
apiVersion: v1
metadata:
  name: food-backend
spec:
  selector:
    app: food-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: main
