apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-frontend
  template:
    metadata:
      labels:
        app: food-frontend
    spec:
      imagePullSecrets:
        - name: registry-key-secret
      containers:
        - name: hello
          image: ghcr.io/pocketcoachfit/food-frontend:v1.5.0
          ports:
            - name: main
              containerPort: 3000
          volumeMounts:
            - name: env-production
              subPath: .env.production
              mountPath: /app/.env.production
      volumes:
        - name: env-production
          configMap:
            name: food-frontend-env-production

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: food-frontend-env-production
data:
  .env.production: |
    NEXT_PUBLIC_FRONTEND_BASEURL = 'https://app.pocketcoach.fit'
    NEXT_PUBLIC_DATA_API_BASEURL = 'https://api.pocketcoach.fit/food/v1'
    NEXT_PUBLIC_STRAPI2_URL = 'https://pocketcoach.fit/secure'
    NEXT_PUBLIC_LOGO_URL = 'https://pocketcoach.fit/img/logo.png'
    NEXT_PUBLIC_FALLBACK_IMAGE_URL = 'https://pocketcoach.fit/img/logo.png'
    CONFIG_ENDPOINT_URL = 'https://pocketcoach.fit/secure/app'

---
kind: Service
apiVersion: v1
metadata:
  name: food-frontend
spec:
  selector:
    app: food-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: main
