apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-index
spec:
  selector:
    matchLabels:
      app: food-index
  replicas: 1
  template:
    metadata:
      labels:
        app: food-index # has to match .spec.selector.matchLabels
    spec:
      imagePullSecrets:
        - name: japimexico-registry
      containers:
        - name: food-index
          image: ghcr.io/pocketcoach/food-index:v1.0.1
          ports:
            - name: main
              containerPort: 3000
          volumeMounts:
            - name: local-envfile
              mountPath: /app/.env.local
      volumes:
        - name: local-envfile
          hostPath:
            path: /secrets/food-index/.env.local
            type: File

---
apiVersion: v1
kind: Service
metadata:
  name: food-index
spec:
  selector:
    app: food-index
  ports:
    - protocol: TCP
      port: 80
      targetPort: main
