apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-frontend
  template:
    metadata:
      labels:
        app: food-frontend
    spec:
      imagePullSecrets:
        - name: registry-key-secret
      containers:
        - name: hello
          image: ghcr.io/pocketcoachfit/food-frontend:v1.10.0
          ports:
            - name: main
              containerPort: 3000
          volumeMounts:
            - name: env-local
              mountPath: /app/.env.local
      # securityContext:
      #   runAsUser: 1001
      #   fsGroup: 1000
      volumes:
        - name: env-local
          hostPath:
            path: /secrets/food-frontend/.env.local
            type: File

---
kind: Service
apiVersion: v1
metadata:
  name: food-frontend
spec:
  selector:
    app: food-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: main
