apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-generator
  template:
    metadata:
      labels:
        app: report-generator
    spec:
      imagePullSecrets:
        - name: registry-key-secret
      containers:
        - name: report-generator
          image: ghcr.io/pocketcoachfit/report-generator-draft:v1.0.0
          ports:
            - name: main
              containerPort: 5000

---
kind: Service
apiVersion: v1
metadata:
  name: report-generator
spec:
  selector:
    app: report-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: main
